### ISSUE TITLE
How to use this plugin in the db-less mode

### ISSUE THREAD

**Issue by aminbaa** [IntelliGrape/kong-plugin-static-response#2]
Hi

I want to return a static response from kong on one of its URLs

I need http://kong-api-gateway:8000/oas to return a json response from `oas.json` or `json.yaml` in the declarative mode

How can I do this?

**Comment by nitinbhadauria** [comment]
Actually, we were trying to avoid using files and local filesystem to make it manageable in scaling setup, so will not work in server-less mode.

But if you have kong setup with DB then you can use something like this for both json and yaml types.

curl -X POST http://{HOST}:8001/services/{SERVICE}/plugins \
    --data "name=static-response"  \
    --data "response_code=200" \
    --data "response_body=@path/to/oas.json" \
    --data "content_type=application/json" \
